// Diccionario espanol -> ingles. Igual que en STAB y Monito: la clave ES el texto en espanol.
// Lo que no este aca se muestra en espanol y app.js lo avisa en la consola (--idioma-faltantes).
// Para comprobar que no falte nada: node _demo/comprobar-textos.js
window.TEXTOS = {
  // ---- ficha ----
  "Programador Full Stack / Arquitecto de software": "Full Stack Developer / Software Architect",
  "Venezuela → Colombia · remoto": "Venezuela → Colombia · remote",
  "ATRIBUTOS": "ATTRIBUTES",
  "MÁX 100": "MAX 100",
  "Hablemos de tu proyecto": "Let's talk about your project",
  "Descargar CV": "Download CV",
  "Correo": "Email",
  "Foto de José Esteban Da Rocha": "Photo of José Esteban Da Rocha",

  // ---- menu ----
  "PROYECTOS": "PROJECTS",
  "CRÓNICA": "TIMELINE",
  "SERVICIOS": "SERVICES",
  "ARTE": "ART",
  "CONTACTO": "CONTACT",

  // ---- portada ----
  "HOJA DE PERSONAJE": "CHARACTER SHEET",
  "Hoja de personaje": "Character sheet", "máx": "max", "Disponible para nuevos proyectos": "Available for new projects",
  "¿Empezamos tu proyecto?": "Ready to start your project?", "Cuéntame la idea y te digo cómo lo hacemos.": "Share your idea and I'll lay out how we'd build it.",
  "Hablemos de": "Let's talk about", "tu proyecto": "your project",
  "o copia el correo": "or copy the address", "Cerrar": "Close", "Ver pieza": "View piece",
  "Cuéntame qué necesitas y te digo sin rodeos si puedo hacerlo. Web, app, backend, videojuego o automatización con IA: si está en mis proyectos, lo hago.": "Tell me what you need and I'll give you a straight answer on whether I can take it on. Website, app, backend, game or AI automation: if it's among my projects, I do it.",
  "Ecosistema de apps": "App ecosystem", "Web y videojuego": "Website and game",
  "Servidor MCP propio · agentes que ejecutan tareas · núcleo IA de FaenApp": "Custom MCP server · agents that run tasks · FaenApp's AI core",
  "Núcleo IA de FaenApp, servidores MCP propios": "FaenApp's AI core, custom MCP servers",
  "2025–26": "2025–26", "2026": "2026", "2024": "2024", "2022": "2022", "2021": "2021", "2020": "2020", "2018": "2018",
  "$200 – $1.200": "$200 – $1,200", "$400 – $2.000": "$400 – $2,000", "$600 – $4.000": "$600 – $4,000", "$1.000 – $6.000": "$1,000 – $6,000",
  "$1.200 – $5.000": "$1,200 – $5,000", "$1.200 – $7.000": "$1,200 – $7,000", "$3.000 – $15.000": "$3,000 – $15,000",
  "De la idea": "From the idea", "a producción.": "to production.",
  "Del arte y el concepto hasta el backend, el servidor y el cliente que paga.": "From art and concept to the backend, the server and the paying customer.",
  "Fundador de FaenApp y cofundador de Monito Amarillo.": "Founder of FaenApp and co-founder of Monito Amarillo.", "Ver los proyectos": "View the projects",
  "Construyo el producto completo y lo pongo en producción.": "I build the whole product and take it live.",
  "Del arte y el concepto hasta el backend, el servidor y el cliente que paga. Fundador de FaenApp y cofundador de Monito Amarillo.": "From art and concept to the backend, the server and the paying customer. Founder of FaenApp and co-founder of Monito Amarillo.",
  "años de experiencia": "years of experience",
  "juegos publicados": "games published",
  "apps en producción": "apps in production",
  "pantallas documentadas": "screens documented",

  // ---- atributos ----
  "Backend": "Backend", "Frontend": "Frontend", "Móvil": "Mobile", "Juegos": "Games", "Arte": "Art", "IA": "AI",
  "LEGENDARIO": "LEGENDARY", "ÉPICO": "EPIC", "RARO": "RARE", "COMÚN": "COMMON",
  "Firestore + endpoints PHP propios · servidor VPS de STAB": "Firestore + custom PHP endpoints · STAB's VPS server",
  "Webapp Vue de FaenApp · 4 webs en vivo": "FaenApp's Vue web app · 4 live websites",
  "Dos apps Flutter firmadas y distribuidas": "Two Flutter apps, signed and distributed",
  "5 juegos publicados · C# + raylib sin motor": "5 published games · C# + raylib, no engine",
  "Pixel art y marca · Spine 2D, Blender, ZBrush, Inkscape": "Pixel art and branding · Spine 2D, Blender, ZBrush, Inkscape",
  "Miles · servidor MCP propio · núcleo IA de FaenApp": "Miles · custom MCP server · FaenApp's AI core",
  "Atributos": "Attributes",
  "Estudios": "Education", "Docencia": "Teaching", "Equipo": "Team",
  "Ingeniería en Sistemas (carrera completa, tesis pendiente).": "Systems Engineering (all coursework completed, thesis pending).",
  "Clases particulares de programación, estructuras de datos y análisis de datos durante toda la carrera.": "Private tutoring in programming, data structures and data analysis throughout my degree.",
  "Dirijo a un desarrollador de interfaz en FaenApp, con revisión y aprobación de cada cambio.": "I lead a UI developer at FaenApp, reviewing and approving every change.",

  // ---- desfile ----
  "Tipo": "Type", "Técnica": "Tech", "Rol": "Role",
  "Producto propio": "Own product", "Videojuego en línea": "Online game", "Herramienta de IA": "AI tool",
  "Estudio": "Studio", "Salud": "Health", "Videojuego": "Video game", "Plataforma web": "Web platform",
  "Sistema de restaurante": "Restaurant system", "Web de cliente": "Client website",
  "SaaS de gestión para negocios de servicios con **clientes pagando**: **dos apps Flutter**, **webapp Vue**, landing, documentación y un mapa de **369 pantallas**. Construido y operado **en solitario**.": "Management SaaS for service businesses with **paying customers**: **two Flutter apps**, a **Vue web app**, landing page, documentation and a **369-screen map**. Built and operated **single-handedly**.",
  "SaaS": "SaaS", "Diseño, desarrollo y operación": "Design, development and operations",
  "Panel de funciones de FaenApp": "FaenApp's feature panel",
  "Juego multijugador comercial escrito en **C# sobre raylib, sin motor**. **Servidor dedicado propio**, cola de emparejamiento real, **ranking** y seis modos. En **beta abierta**.": "Commercial multiplayer game written in **C# on raylib, no engine**. **Self-hosted dedicated server**, real matchmaking queue, **leaderboard** and six modes. Now in **open beta**.",
  "Programación, arte y servidor": "Programming, art and server",
  "Partida de Stab Your Friends": "A Stab Your Friends match",
  "Sala de mando para trabajar con varios asistentes de IA a la vez, con un motor de flujos por nodos que de verdad se ejecutan y generación de imágenes.": "A command room for working with several AI assistants at once, with a node-based flow engine that actually runs, plus image generation.",
  "Herramienta interna": "Internal tool", "Node · MCP · varios modelos": "Node · MCP · several models", "Diseño y desarrollo": "Design and development",
  "Miles, sala de mando multiagente": "Miles, multi-agent command room",
  "Estudio de videojuegos que fundé con un amigo de hace **más de 17 años**, cada uno a un lado de la frontera entre Colombia y Venezuela. Hacemos juegos **divertidos** para jugar **con amigos**, en local u online, **sin motor y sin plantillas**. Yo llevo **todo lo técnico**: web, marca, cuentas, pagos y servidor.": "Game studio I founded with a friend of **more than 17 years**, each of us on one side of the Colombia–Venezuela border. We make **fun** games to play **with friends**, locally or online, **with no engine and no templates**. I handle **everything technical**: website, brand, accounts, payments and server.",
  "Estudio de videojuegos": "Game studio", "HTML · JS · PHP · Wompi · VPS": "HTML · JS · PHP · Wompi · VPS", "Cofundador y todo lo técnico": "Co-founder and all things technical",
  "Logo de Monito Amarillo": "Monito Amarillo logo",
  "Consultas médicas a domicilio con solicitud en vivo, tipo Uber: el paciente pide, el médico acepta. Recetas, historiales e incapacidades, con una app por cada lado.": "House-call medical visits requested live, Uber-style: the patient requests, the doctor accepts. Prescriptions, medical records and sick notes, with a separate app for each side.",
  "Apps Android": "Android apps", "Desarrollador del sistema completo": "Developer of the entire system",
  "Pantalla de Momi Medic": "Momi Medic screenshot",
  "Roguelike frenético de supervivencia por oleadas: defender la Tierra de una invasión con una nave indestructible. Demo publicada.": "Frantic wave-survival roguelike: defend Earth from an invasion with an indestructible ship. Demo released.",
  "Programación y arte": "Programming and art", "Portada de Earth Survivor": "Earth Survivor cover art",
  "Juego idle de farmeo infinito con misiones, ambientado en el mundo vikingo.": "Idle game with endless farming and quests, set in a Viking world.",
  "Portada de Idle of Tyr": "Idle of Tyr cover art",
  "Arcade shoot 'em up: sobrevive a oleadas de enemigos y acumula puntos mientras mejoras tu nave.": "Arcade shoot 'em up: survive waves of enemies and rack up points while upgrading your ship.",
  "Portada de Space G": "Space G cover art",
  "Mi primer juego publicado: plataformas con oleadas infinitas donde la meta es sobrevivir el mayor tiempo posible.": "My first published game: a platformer with endless waves where the goal is to survive as long as you can.",
  "Videojuego · PC": "Video game · PC", "Portada de Mad King": "Mad King cover art",
  "Comida a domicilio para Valera, Trujillo (Venezuela): una plataforma de pedidos hecha a medida para una ciudad sin cobertura de las grandes apps.": "Food delivery for Valera, Trujillo (Venezuela): a custom ordering platform for a city the big apps never reached.",
  "Desarrollador del proyecto completo": "Developer of the entire project", "Pantalla de Ready": "Ready screenshot",
  "Administración de un restaurante y bar con pedidos por código QR en cada mesa, para depender menos de los meseros. Mi primer sistema en producción.": "Restaurant and bar management with QR-code ordering at every table, so the business relies less on waiters. My first system in production.",
  "Sistema web": "Web system", "PHP · MySQL · JS · wireframes propios": "PHP · MySQL · JS · custom wireframes", "Pantalla de La Castañuela": "La Castañuela screenshot",
  "Plataforma de subastas con ofertas en vivo, cuenta regresiva e historial de pujas por producto.": "Auction platform with live bidding, countdown and bid history per product.",
  "Firestore · tiempo real": "Firestore · real time", "Desarrollador": "Developer", "Demo": "Demo",
  "Plataforma de subastas en tiempo real": "Real-time auction platform",
  "Web educativa sobre lesiones por adhesivos médicos, para una enfermera de la Universidad del Valle. Publicada.": "Educational website on medical-adhesive injuries, for a nurse at Universidad del Valle. Live.",
  "Web educativa": "Educational website", "Portada de MARSICARE": "MARSICARE home page", "Ver la web": "Visit the site",
  "Ver FaenApp": "Visit FaenApp", "Ver la web del juego": "Visit the game's website", "Visitar el estudio": "Visit the studio", "Ver en itch.io": "View on itch.io",

  // ---- claves que usa app.js (no cambiar la clave) ----
  "captura pendiente": "screenshot coming soon",
  "Hecho sin IA": "Built without AI",
  "Destacado": "Featured",
  "Más información": "More details",
  "Toca la carta para ver más": "Tap the card to see more",
  "Proyecto privado · sin enlace": "Private project · no link",
  "Cargando hoja de personaje": "Loading character sheet",
  "Anterior": "Previous", "Siguiente": "Next",
  "Ranking mundial ahora": "World ranking right now",
  "pts": "pts",

  // ---- cronica ----
  "Crónica": "Timeline",
  "Restaurante con pedidos por QR en cada mesa": "Restaurant with QR ordering at every table",
  "Comida a domicilio para Valera, Trujillo": "Food delivery for Valera, Trujillo",
  "Mi primer juego publicado": "My first published game",
  "Arcade shoot 'em up": "Arcade shoot 'em up",
  "RPG idle vikingo": "Viking idle RPG",
  "Consultas médicas a domicilio": "House-call medical visits",
  "Demo publicada": "Demo released",
  "Nace mi propio SaaS": "My own SaaS is born",
  "Estudio en vivo desde el 8 de septiembre": "Studio live since September 8",
  "Beta abierta": "Open beta",
  "En producción, con clientes pagando": "In production, with paying customers",

  // ---- servicios ----
  "Servicios freelance": "Freelance services",
  "piso y techo": "floor and ceiling",
  "Prueba": "Proof",
  "Identidad visual / logos": "Visual identity / logos",
  "Logotipos, mascotas y propuestas de marca": "Logos, mascots and brand concepts",
  "Documentación de producto": "Product documentation",
  "Manuales, capturas y mapas de pantallas": "Manuals, screenshots and screen maps",
  "Página web a medida": "Custom website",
  "Diseño, desarrollo y publicación. Bilingüe si lo necesitas": "Design, development and launch. Bilingual if you need it",
  "monitoamarillo.com, la web de STAB, faenapp.com, MARSICARE": "monitoamarillo.com, STAB's website, faenapp.com, MARSICARE",
  "Backend e infraestructura": "Backend and infrastructure",
  "Base de datos, endpoints propios, VPS, almacenamiento de archivos": "Database, custom endpoints, VPS, file storage",
  "Backend de FaenApp, servidor de STAB": "FaenApp's backend, STAB's server",
  "Catálogo y pedidos en línea": "Online catalog and orders",
  "Catálogo público, pedidos, reservas, QR por mesa": "Public catalog, orders, reservations, QR per table",
  "Catálogo de FaenApp, La Castañuela": "FaenApp's catalog, La Castañuela",
  "Automatización con IA": "AI automation",
  "Agentes que ejecutan tareas, servidores MCP, orquestación de modelos": "Agents that run tasks, MCP servers, model orchestration",
  "Miles, núcleo IA de FaenApp": "Miles, FaenApp's AI core",
  "App móvil Android": "Android mobile app",
  "Flutter, firmada, distribuida y con actualizaciones integradas": "Flutter, signed, distributed, with built-in updates",
  "FaenApp Admins y Empleado, Momi Medic": "FaenApp Admins and Employee, Momi Medic",
  "Desarrollo de videojuegos": "Game development",
  "Unity o motor propio; gameplay y multijugador con servidor": "Unity or custom engine; gameplay and server-based multiplayer",
  "5 juegos publicados, Stab Your Friends": "5 published games, Stab Your Friends",
  "desde $5.000": "from $5,000", "según alcance": "depending on scope",
  "Por hora, para tareas puntuales": "Hourly, for one-off tasks",
  "Fritas, Frigomax, Hoguera, Ninja Store, ULA FC": "Fritas, Frigomax, Hoguera, Ninja Store, ULA FC",
  "faenapp.com/docs, mapa de 369 pantallas": "faenapp.com/docs, 369-screen map",

  // ---- arte ----
  "Pixel art, logotipos y mascotas. Sin explicaciones: solo las piezas.": "Pixel art, logos and mascots. No commentary, just the pieces.",
  "Pieza de arte": "Artwork",

  // ---- contacto ----
  "Copiar": "Copy", "Copiado": "Copied",
  "Escríbeme": "Email me",
  "Así se veía antes": "How it used to look",
  "hecho a mano": "handmade",
  "versión": "version",

  // ---- iguales en los dos idiomas (tecnologias y direcciones): estan para que no avisen ----
  "Flutter · Vue · Node · Firestore · PHP": "Flutter · Vue · Node · Firestore · PHP",
  "C# · .NET 9 · raylib · PHP · VPS": "C# · .NET 9 · raylib · PHP · VPS",
  "Android Studio · Firebase": "Android Studio · Firebase",
  "Unity · C#": "Unity · C#",
  "PHP · MySQL · JS": "PHP · MySQL · JS",
  "HTML · CSS · JS · GitHub Pages": "HTML · CSS · JS · GitHub Pages",
  "faenapp.com": "faenapp.com",
  "monitoamarillo.com/stab": "monitoamarillo.com/stab",
  "monitoamarillo.com": "monitoamarillo.com",
  "seinp.itch.io": "seinp.itch.io",
  "$35 – $60 / h": "$35 – $60 / h"
};
