// Diccionario espanol -> ingles. Igual que en STAB y Monito: la clave ES el texto en espanol.
// Lo que no este aca se muestra en espanol y app.js lo avisa en la consola (--idioma-faltantes).
window.TEXTOS = {
  // ---- ficha ----
  "Programador Full Stack / Arquitecto de software": "Full Stack Developer / Software Architect",
  "Venezuela → Colombia · remoto": "Venezuela → Colombia · remote",
  "ATRIBUTOS": "ATTRIBUTES",
  "MÁX 100": "MAX 100",
  "Hablemos de tu proyecto": "Let's talk about your project",
  "Descargar CV": "Download CV",
  "Correo": "Email",
  "Foto de José Esteban Da Rocha": "Photo of José Esteban Da Rocha",

  // ---- menu ----
  "DESFILE": "PARADE",
  "CRÓNICA": "TIMELINE",
  "SERVICIOS": "SERVICES",
  "ARTE": "ART",
  "CONTACTO": "CONTACT",

  // ---- portada ----
  "HOJA DE PERSONAJE": "CHARACTER SHEET",
  "Construyo el producto completo y lo pongo en producción.": "I build the complete product and put it into production.",
  "Del arte y el concepto hasta el backend, el servidor y el cliente que paga. Dueño de FaenApp y cofundador de Monito Amarillo.": "From the art and the concept to the backend, the server and the paying customer. Owner of FaenApp and co-founder of Monito Amarillo.",
  "años de experiencia": "years of experience",
  "juegos publicados": "games published",
  "apps en producción": "apps in production",
  "versión de STAB": "STAB version",
  "pantallas documentadas": "screens documented",

  // ---- atributos ----
  "Backend": "Backend", "Frontend": "Frontend", "Móvil": "Mobile", "Juegos": "Games", "Arte": "Art", "IA": "AI",
  "LEGENDARIO": "LEGENDARY", "ÉPICO": "EPIC", "RARO": "RARE", "COMÚN": "COMMON",
  "Firestore + endpoints PHP propios · servidor VPS de STAB": "Firestore + custom PHP endpoints · STAB's VPS server",
  "Webapp Vue de FaenApp · 4 webs en vivo": "FaenApp's Vue webapp · 4 live websites",
  "Dos apps Flutter firmadas y distribuidas": "Two signed and distributed Flutter apps",
  "5 juegos publicados · C# + raylib sin motor": "5 published games · C# + raylib, no engine",
  "Pixel art y marca · Spine 2D, Blender, ZBrush, Inkscape": "Pixel art and branding · Spine 2D, Blender, ZBrush, Inkscape",
  "Miles · servidor MCP propio · núcleo IA de FaenApp": "Miles · custom MCP server · FaenApp's AI core",
  "Atributos": "Attributes",
  "Estudios": "Education", "Docencia": "Teaching", "Equipo": "Team",
  "Ingeniería en Sistemas (carrera completa, tesis pendiente).": "Systems Engineering (full degree coursework, thesis pending).",
  "Clases privadas de programación, estructura de datos y análisis de datos durante una carrera entera.": "Private lessons in programming, data structures and data analysis through an entire degree.",
  "Dirige a un desarrollador de interfaz en FaenApp, con procedimiento de aprobación.": "Leads a UI developer at FaenApp, with an approval procedure.",

  // ---- desfile ----
  "Tipo": "Type", "Técnica": "Tech", "Rol": "Role",
  "Producto propio": "Own product", "Videojuego en línea": "Online game", "Herramienta de IA": "AI tool",
  "Estudio": "Studio", "Salud": "Health", "Videojuego": "Video game", "Plataforma web": "Web platform",
  "Sistema de restaurante": "Restaurant system", "Web de cliente": "Client website",
  "SaaS de gestión para negocios de servicios con **clientes pagando**: **dos apps Flutter**, **webapp Vue**, landing, documentación y un mapa de **369 pantallas**. Construido y operado **en solitario**.": "Business management SaaS for service businesses, with **paying customers**: **two Flutter apps**, a **Vue webapp**, landing page, documentation and a **369-screen map**. Built and operated **single-handedly**.",
  "SaaS": "SaaS", "Diseño, desarrollo y operación": "Design, development and operations",
  "Panel de funciones de FaenApp": "FaenApp's feature panel",
  "Multijugador comercial escrito en **C# sobre raylib, sin motor**. **Servidor dedicado propio**, cola de emparejamiento real, **ranking** y seis modos. En **beta abierta**.": "Commercial multiplayer game written in **C# on raylib, no engine**. **Own dedicated server**, real matchmaking queue, **ranking** and six modes. In **open beta**.",
  "Programación, arte y servidor": "Programming, art and server",
  "Partida de Stab Your Friends": "A Stab Your Friends match",
  "Sala de mando para trabajar con varios asistentes de IA a la vez, con un motor de flujos por nodos que de verdad se ejecutan y generación de imágenes.": "A command room for working with several AI assistants at once, with a node-based flow engine that actually executes, and image generation.",
  "Herramienta interna": "Internal tool", "Node · MCP · varios modelos": "Node · MCP · several models", "Diseño y desarrollo": "Design and development",
  "Miles, sala de mando multiagente": "Miles, multi-agent command room",
  "Estudio de videojuegos de dos personas, con arte hecho a mano. La web del estudio y la del juego están en línea.": "A two-person game studio with hand-made art. The studio's website and the game's are live.",
  "Estudio de videojuegos": "Game studio", "Web · marca · publicación": "Web · branding · publishing", "Cofundador y todo lo técnico": "Co-founder and everything technical",
  "Logo de Monito Amarillo": "Monito Amarillo logo",
  "Consultas médicas a domicilio con solicitud en vivo, tipo Uber: el paciente pide, el médico acepta. Recetas, historiales e incapacidades, con una app por cada lado.": "House-call medical consultations with live requests, Uber-style: the patient asks, the doctor accepts. Prescriptions, records and sick notes, with one app per side.",
  "Apps Android": "Android apps", "Desarrollador del sistema completo": "Developer of the whole system",
  "Pantalla de Momi Medic": "A Momi Medic screen",
  "Roguelike frenético de supervivencia por oleadas: defender la Tierra de una invasión con una nave indestructible. Demo publicada.": "Frantic wave-survival roguelike: defend Earth from an invasion with an indestructible ship. Demo published.",
  "Programación y arte": "Programming and art", "Portada de Earth Survivor": "Earth Survivor cover",
  "AFK farming infinito con misiones, ambientado en los nórdicos vikingos.": "Endless AFK farming with quests, set among the Norse Vikings.",
  "Portada de Idle of Tyr": "Idle of Tyr cover",
  "Arcade shoot'em up: sobrevivir a oleadas de enemigos y acumular puntos mientras mejorás tu nave.": "Arcade shoot'em up: survive waves of enemies and rack up points while upgrading your ship.",
  "Portada de Space G": "Space G cover",
  "El primer juego publicado: plataformas con oleadas infinitas donde sobrevivir el mayor tiempo posible es la clave.": "The first published game: a platformer with endless waves where surviving as long as possible is the key.",
  "Videojuego · PC": "Video game · PC", "Portada de Mad King": "Mad King cover",
  "Comida a domicilio para Valera, Trujillo (Venezuela): una plataforma de pedidos hecha a medida para una ciudad sin cobertura de las grandes apps.": "Food delivery for Valera, Trujillo (Venezuela): an ordering platform built for a city the big apps never covered.",
  "Desarrollador del proyecto completo": "Developer of the complete project", "Pantalla de Ready": "A Ready screen",
  "Administración de un restaurante y bar con pedidos por código QR en cada mesa, para depender menos de los meseros. El primer sistema en producción.": "Management of a restaurant and bar with QR-code ordering at every table, to depend less on waiters. The first system in production.",
  "Sistema web": "Web system", "PHP · MySQL · JS · wireframes propios": "PHP · MySQL · JS · own wireframes", "Pantalla de La Castañuela": "A La Castañuela screen",
  "Plataforma de subastas con ofertas en vivo, cuenta regresiva e historial de pujas por producto.": "Auction platform with live bids, countdown and bid history per product.",
  "Firestore · tiempo real": "Firestore · real time", "Desarrollador": "Developer", "Demo": "Demo",
  "Plataforma de subastas en tiempo real": "Real-time auction platform",
  "Web educativa sobre lesiones por adhesivos médicos, para una enfermera de la Universidad del Valle. Publicada.": "Educational website about medical-adhesive injuries, for a nurse at Universidad del Valle. Published.",
  "Web educativa": "Educational website", "Portada de MARSICARE": "MARSICARE cover", "Ver la web": "Visit the site",
  "Ver FaenApp": "See FaenApp", "Ver la web del juego": "See the game's website", "Visitar el estudio": "Visit the studio", "Ver en itch.io": "See it on itch.io",
  "captura pendiente": "screenshot pending",
  "Hecho sin IA": "Made without AI",
  "Destacado": "Featured",
  "Más información": "More information",
  "Tocá la carta para ver más": "Tap the card to see more",
  "Anterior": "Previous", "Siguiente": "Next",
  "Ranking mundial ahora": "World ranking right now",
  "pts": "pts",

  // ---- cronica ----
  "Crónica": "Timeline",
  "Restaurante con pedidos por QR en cada mesa": "Restaurant with QR ordering at every table",
  "Comida a domicilio para Valera, Trujillo": "Food delivery for Valera, Trujillo",
  "El primer juego publicado": "The first published game",
  "Arcade shoot'em up": "Arcade shoot'em up",
  "RPG idle vikingo": "Viking idle RPG",
  "Consultas médicas a domicilio": "House-call medical consultations",
  "Demo publicada": "Demo published",
  "Nace el SaaS propio": "The own SaaS is born",
  "Estudio en vivo desde el 8 de septiembre": "Studio live since September 8",
  "Beta abierta": "Open beta",
  "En producción, con clientes pagando": "In production, with paying customers",

  // ---- servicios ----
  "Servicios freelance": "Freelance services",
  "piso y techo": "floor and ceiling",
  "Prueba": "Proof",
  "Identidad visual / logos": "Visual identity / logos",
  "Logotipos, mascotas y propuestas de marca": "Logos, mascots and brand proposals",
  "Documentación de producto": "Product documentation",
  "Manuales, capturas y mapas de pantallas": "Manuals, screenshots and screen maps",
  "Página web a medida": "Custom website",
  "Diseño, desarrollo y publicación. Bilingüe si se pide": "Design, development and publishing. Bilingual on request",
  "monitoamarillo.com, la web de STAB, faenapp.com, MARSICARE": "monitoamarillo.com, STAB's website, faenapp.com, MARSICARE",
  "Backend e infraestructura": "Backend and infrastructure",
  "Base de datos, endpoints propios, VPS, almacenamiento de archivos": "Database, custom endpoints, VPS, file storage",
  "Backend de FaenApp, servidor de STAB": "FaenApp's backend, STAB's server",
  "Catálogo y pedidos en línea": "Online catalogue and orders",
  "Catálogo público, pedidos, reservas, QR por mesa": "Public catalogue, orders, bookings, QR per table",
  "Catálogo de FaenApp, La Castañuela": "FaenApp's catalogue, La Castañuela",
  "Automatización con IA": "AI automation",
  "Agentes que ejecutan tareas, servidores MCP, orquestación de modelos": "Agents that execute tasks, MCP servers, model orchestration",
  "Miles, núcleo IA de FaenApp": "Miles, FaenApp's AI core",
  "App móvil Android": "Android mobile app",
  "Flutter, firmada, distribuida y con actualizaciones": "Flutter, signed, distributed and with updates",
  "FaenApp Admins y Empleado, Momi Medic": "FaenApp Admins and Employee, Momi Medic",
  "Desarrollo de videojuegos": "Game development",
  "Unity o motor propio; gameplay y multijugador con servidor": "Unity or own engine; gameplay and multiplayer with server",
  "5 juegos publicados, Stab Your Friends": "5 published games, Stab Your Friends",
  "desde $5.000": "from $5,000", "según alcance": "depending on scope",
  "Por hora, para trabajo suelto": "Hourly, for loose work",
  "Fritas, Frigomax, Hoguera, Ninja Store, ULA FC": "Fritas, Frigomax, Hoguera, Ninja Store, ULA FC",
  "faenapp.com/docs, mapa de 369 pantallas": "faenapp.com/docs, 369-screen map",

  // ---- arte ----
  "Pixel art, logotipos y mascotas. Sin explicaciones: solo las piezas.": "Pixel art, logos and mascots. No explanations: just the pieces.",
  "Pieza de arte": "Art piece",

  // ---- contacto ----
  "Contame qué necesitás y te digo si puedo con eso. Respondo el mismo día.": "Tell me what you need and I'll tell you if I can take it. I reply the same day.",
  "Copiar": "Copy", "Copiado": "Copied",
  "Escribime": "Write to me",
  "Así se veía antes": "How it looked before",
  "hecho a mano": "hand made",
  "versión": "version",

  // ---- iguales en los dos idiomas (tecnologias y direcciones): estan para que no avisen ----
  "Flutter · Vue · Node · Firestore · PHP": "Flutter · Vue · Node · Firestore · PHP",
  "C# · .NET 9 · raylib · PHP · VPS": "C# · .NET 9 · raylib · PHP · VPS",
  "Android Studio · Firebase": "Android Studio · Firebase",
  "Unity · C#": "Unity · C#",
  "PHP · MySQL · JS": "PHP · MySQL · JS",
  "HTML · CSS · JS · GitHub Pages": "HTML · CSS · JS · GitHub Pages",
  "faenapp.com": "faenapp.com",
  "monitoamarillo.com/stab": "monitoamarillo.com/stab",
  "monitoamarillo.com": "monitoamarillo.com",
  "seinp.itch.io": "seinp.itch.io",
  "$35 – $60 / h": "$35 – $60 / h"
};
